In [17]:
#Importer lespackages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [2]:
#Lire la base de donn√©es
bd=pd.read_csv('/LoanExport.csv')
bd

<ipython-input-2-25b70e14eb7c>:2: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  bd=pd.read_csv('/LoanExport.csv')

,CreditScore,FirstPaymentDate,FirstTimeHomebuyer,MaturityDate,MSA,MIP,Units,Occupancy,OCLTV,DTI,...,PostalCode,LoanSeqNum,LoanPurpose,OrigLoanTerm,NumBorrowers,SellerName,ServicerName,EverDelinquent,MonthsDelinquent,MonthsInRepayment
0,0,199902,N,202901,16974,25,1,O,89,27,...,60400,F199Q1268030,P,360,2,FL,WASHINGTONMUTUALBANK,0,0,52
1,0,199902,N,202901,19740,0,1,O,73,17,...,80200,F199Q1015092,N,360,1,FT,CHASEHOMEFINANCELLC,0,0,144
2,0,199902,N,202901,29940,0,1,O,75,16,...,66000,F199Q1266886,N,360,2,FL,WASHINGTONMUTUALBANK,0,0,67
3,0,199902,N,202901,31084,0,1,O,76,14,...,90700,F199Q1178167,N,360,2,GM,GMACMTGECORP,0,0,35
4,0,199902,N,202901,35644,0,1,O,78,18,...,7600,F199Q1178517,N,360,2,GM,GMACMTGECORP,0,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291446,839,199903,N,202902,37964,0,1,O,60,32,...,19400,F199Q1220925,N,360,2,Ot,Other servicers,0,0,12
291447,840,200210,N,202904,35644,0,1,O,73,0,...,11600,F199Q1401332,P,319,2,Ot,Other servicers,0,0,53
291448,840,200304,N,202904,42044,0,1,O,73,31,...,92800,F199Q1401282,N,313,1,Ot,Other servicers,0,0,38
291449,845,199904,N,202903,37964,0,1,I,80,54,...,19300,F199Q1220924,P,360,2,Ot,Other servicers,0,0,32
291450,849,199903,N,202902,37964,0,1,O,47,29,...,18900,F199Q1220923,P,360,2,Ot,Other servicers,0,0,29

In [5]:
#1. Data Cleaning:
#Identify
bd.isnull().sum()

CreditScore               0
FirstPaymentDate          0
FirstTimeHomebuyer        0
MaturityDate              0
MSA                       0
MIP                       0
Units                     0
Occupancy                 0
OCLTV                     0
DTI                       0
OrigUPB                   0
LTV                       0
OrigInterestRate          0
Channel                   0
PPM                       0
ProductType               0
PropertyState             0
PropertyType              0
PostalCode                0
LoanSeqNum                0
LoanPurpose               0
OrigLoanTerm              0
NumBorrowers              0
SellerName            24994
ServicerName              0
EverDelinquent            0
MonthsDelinquent          0
MonthsInRepayment         0
dtype: int64

In [9]:
#  handle missing values
bd.dropna(inplace=True)
bd

,CreditScore,FirstPaymentDate,FirstTimeHomebuyer,MaturityDate,MSA,MIP,Units,Occupancy,OCLTV,DTI,...,PostalCode,LoanSeqNum,LoanPurpose,OrigLoanTerm,NumBorrowers,SellerName,ServicerName,EverDelinquent,MonthsDelinquent,MonthsInRepayment
0,0,199902,N,202901,16974,25,1,O,89,27,...,60400,F199Q1268030,P,360,2,FL,WASHINGTONMUTUALBANK,0,0,52
1,0,199902,N,202901,19740,0,1,O,73,17,...,80200,F199Q1015092,N,360,1,FT,CHASEHOMEFINANCELLC,0,0,144
2,0,199902,N,202901,29940,0,1,O,75,16,...,66000,F199Q1266886,N,360,2,FL,WASHINGTONMUTUALBANK,0,0,67
3,0,199902,N,202901,31084,0,1,O,76,14,...,90700,F199Q1178167,N,360,2,GM,GMACMTGECORP,0,0,35
4,0,199902,N,202901,35644,0,1,O,78,18,...,7600,F199Q1178517,N,360,2,GM,GMACMTGECORP,0,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291446,839,199903,N,202902,37964,0,1,O,60,32,...,19400,F199Q1220925,N,360,2,Ot,Other servicers,0,0,12
291447,840,200210,N,202904,35644,0,1,O,73,0,...,11600,F199Q1401332,P,319,2,Ot,Other servicers,0,0,53
291448,840,200304,N,202904,42044,0,1,O,73,31,...,92800,F199Q1401282,N,313,1,Ot,Other servicers,0,0,38
291449,845,199904,N,202903,37964,0,1,I,80,54,...,19300,F199Q1220924,P,360,2,Ot,Other servicers,0,0,32
291450,849,199903,N,202902,37964,0,1,O,47,29,...,18900,F199Q1220923,P,360,2,Ot,Other servicers,0,0,29

In [11]:
# Remove duplicates
bd.drop_duplicates(inplace=True)
bd

,CreditScore,FirstPaymentDate,FirstTimeHomebuyer,MaturityDate,MSA,MIP,Units,Occupancy,OCLTV,DTI,...,PostalCode,LoanSeqNum,LoanPurpose,OrigLoanTerm,NumBorrowers,SellerName,ServicerName,EverDelinquent,MonthsDelinquent,MonthsInRepayment
0,0,199902,N,202901,16974,25,1,O,89,27,...,60400,F199Q1268030,P,360,2,FL,WASHINGTONMUTUALBANK,0,0,52
1,0,199902,N,202901,19740,0,1,O,73,17,...,80200,F199Q1015092,N,360,1,FT,CHASEHOMEFINANCELLC,0,0,144
2,0,199902,N,202901,29940,0,1,O,75,16,...,66000,F199Q1266886,N,360,2,FL,WASHINGTONMUTUALBANK,0,0,67
3,0,199902,N,202901,31084,0,1,O,76,14,...,90700,F199Q1178167,N,360,2,GM,GMACMTGECORP,0,0,35
4,0,199902,N,202901,35644,0,1,O,78,18,...,7600,F199Q1178517,N,360,2,GM,GMACMTGECORP,0,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291446,839,199903,N,202902,37964,0,1,O,60,32,...,19400,F199Q1220925,N,360,2,Ot,Other servicers,0,0,12
291447,840,200210,N,202904,35644,0,1,O,73,0,...,11600,F199Q1401332,P,319,2,Ot,Other servicers,0,0,53
291448,840,200304,N,202904,42044,0,1,O,73,31,...,92800,F199Q1401282,N,313,1,Ot,Other servicers,0,0,38
291449,845,199904,N,202903,37964,0,1,I,80,54,...,19300,F199Q1220924,P,360,2,Ot,Other servicers,0,0,32
291450,849,199903,N,202902,37964,0,1,O,47,29,...,18900,F199Q1220923,P,360,2,Ot,Other servicers,0,0,29

In [14]:
#Correct data types :
# Conversion des colonnes num√©riques
bd['CreditScore'] = bd['CreditScore'].astype('int')
bd['FirstPaymentDate'] = pd.to_datetime(bd['FirstPaymentDate'], format='%Y%m')
bd['MaturityDate'] = pd.to_datetime(bd['MaturityDate'], format='%Y%m')
bd['OrigUPB'] = bd['OrigUPB'].astype('int')
bd['OrigInterestRate'] = bd['OrigInterestRate'].astype('float')

# Conversion des colonnes cat√©gorielles
bd['FirstTimeHomebuyer'] = bd['FirstTimeHomebuyer'].astype('category')
bd['Channel'] = bd['Channel'].astype('category')
bd['ProductType'] = bd['ProductType'].astype('category')
bd['PropertyState'] = bd['PropertyState'].astype('category')
bd['PropertyType'] = bd['PropertyType'].astype('category')
bd['SellerName'] = bd['SellerName'].astype('category')
bd['ServicerName'] = bd['ServicerName'].astype('category')
bd

,CreditScore,FirstPaymentDate,FirstTimeHomebuyer,MaturityDate,MSA,MIP,Units,Occupancy,OCLTV,DTI,...,PostalCode,LoanSeqNum,LoanPurpose,OrigLoanTerm,NumBorrowers,SellerName,ServicerName,EverDelinquent,MonthsDelinquent,MonthsInRepayment
0,0,1999-02-01,N,2029-01-01,16974,25,1,O,89,27,...,60400,F199Q1268030,P,360,2,FL,WASHINGTONMUTUALBANK,0,0,52
1,0,1999-02-01,N,2029-01-01,19740,0,1,O,73,17,...,80200,F199Q1015092,N,360,1,FT,CHASEHOMEFINANCELLC,0,0,144
2,0,1999-02-01,N,2029-01-01,29940,0,1,O,75,16,...,66000,F199Q1266886,N,360,2,FL,WASHINGTONMUTUALBANK,0,0,67
3,0,1999-02-01,N,2029-01-01,31084,0,1,O,76,14,...,90700,F199Q1178167,N,360,2,GM,GMACMTGECORP,0,0,35
4,0,1999-02-01,N,2029-01-01,35644,0,1,O,78,18,...,7600,F199Q1178517,N,360,2,GM,GMACMTGECORP,0,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291446,839,1999-03-01,N,2029-02-01,37964,0,1,O,60,32,...,19400,F199Q1220925,N,360,2,Ot,Other servicers,0,0,12
291447,840,2002-10-01,N,2029-04-01,35644,0,1,O,73,0,...,11600,F199Q1401332,P,319,2,Ot,Other servicers,0,0,53
291448,840,2003-04-01,N,2029-04-01,42044,0,1,O,73,31,...,92800,F199Q1401282,N,313,1,Ot,Other servicers,0,0,38
291449,845,1999-04-01,N,2029-03-01,37964,0,1,I,80,54,...,19300,F199Q1220924,P,360,2,Ot,Other servicers,0,0,32
291450,849,1999-03-01,N,2029-02-01,37964,0,1,O,47,29,...,18900,F199Q1220923,P,360,2,Ot,Other servicers,0,0,29

In [19]:
#2. Data Encoding:
le = LabelEncoder()
bd['FirstTimeHomebuyer'] = le.fit_transform(bd['FirstTimeHomebuyer'])
bd['Channel'] = le.fit_transform(bd['Channel'])
bd['ProductType'] = le.fit_transform(bd['ProductType'])
bd['PropertyState'] = le.fit_transform(bd['PropertyState'])
bd['PropertyType'] = le.fit_transform(bd['PropertyType'])
bd['SellerName'] = le.fit_transform(bd['SellerName'])
bd['ServicerName'] = le.fit_transform(bd['ServicerName'])
bd

,CreditScore,FirstPaymentDate,FirstTimeHomebuyer,MaturityDate,MSA,MIP,Units,Occupancy,OCLTV,DTI,...,PostalCode,LoanSeqNum,LoanPurpose,OrigLoanTerm,NumBorrowers,SellerName,ServicerName,EverDelinquent,MonthsDelinquent,MonthsInRepayment
0,0,1999-02-01,0,2029-01-01,16974,25,1,O,89,27,...,60400,F199Q1268030,P,360,2,7,17,0,0,52
1,0,1999-02-01,0,2029-01-01,19740,0,1,O,73,17,...,80200,F199Q1015092,N,360,1,8,3,0,0,144
2,0,1999-02-01,0,2029-01-01,29940,0,1,O,75,16,...,66000,F199Q1266886,N,360,2,7,17,0,0,67
3,0,1999-02-01,0,2029-01-01,31084,0,1,O,76,14,...,90700,F199Q1178167,N,360,2,10,10,0,0,35
4,0,1999-02-01,0,2029-01-01,35644,0,1,O,78,18,...,7600,F199Q1178517,N,360,2,10,10,0,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291446,839,1999-03-01,0,2029-02-01,37964,0,1,O,60,32,...,19400,F199Q1220925,N,360,2,14,14,0,0,12
291447,840,2002-10-01,0,2029-04-01,35644,0,1,O,73,0,...,11600,F199Q1401332,P,319,2,14,14,0,0,53
291448,840,2003-04-01,0,2029-04-01,42044,0,1,O,73,31,...,92800,F199Q1401282,N,313,1,14,14,0,0,38
291449,845,1999-04-01,0,2029-03-01,37964,0,1,I,80,54,...,19300,F199Q1220924,P,360,2,14,14,0,0,32
291450,849,1999-03-01,0,2029-02-01,37964,0,1,O,47,29,...,18900,F199Q1220923,P,360,2,14,14,0,0,29

In [20]:
#3. Data Labelling:
# S√©parer les caract√©ristiques et la cible
target = bd['EverDelinquent']
features = bd.drop('EverDelinquent', axis=1)
bd

,CreditScore,FirstPaymentDate,FirstTimeHomebuyer,MaturityDate,MSA,MIP,Units,Occupancy,OCLTV,DTI,...,PostalCode,LoanSeqNum,LoanPurpose,OrigLoanTerm,NumBorrowers,SellerName,ServicerName,EverDelinquent,MonthsDelinquent,MonthsInRepayment
0,0,1999-02-01,0,2029-01-01,16974,25,1,O,89,27,...,60400,F199Q1268030,P,360,2,7,17,0,0,52
1,0,1999-02-01,0,2029-01-01,19740,0,1,O,73,17,...,80200,F199Q1015092,N,360,1,8,3,0,0,144
2,0,1999-02-01,0,2029-01-01,29940,0,1,O,75,16,...,66000,F199Q1266886,N,360,2,7,17,0,0,67
3,0,1999-02-01,0,2029-01-01,31084,0,1,O,76,14,...,90700,F199Q1178167,N,360,2,10,10,0,0,35
4,0,1999-02-01,0,2029-01-01,35644,0,1,O,78,18,...,7600,F199Q1178517,N,360,2,10,10,0,0,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291446,839,1999-03-01,0,2029-02-01,37964,0,1,O,60,32,...,19400,F199Q1220925,N,360,2,14,14,0,0,12
291447,840,2002-10-01,0,2029-04-01,35644,0,1,O,73,0,...,11600,F199Q1401332,P,319,2,14,14,0,0,53
291448,840,2003-04-01,0,2029-04-01,42044,0,1,O,73,31,...,92800,F199Q1401282,N,313,1,14,14,0,0,38
291449,845,1999-04-01,0,2029-03-01,37964,0,1,I,80,54,...,19300,F199Q1220924,P,360,2,14,14,0,0,32
291450,849,1999-03-01,0,2029-02-01,37964,0,1,O,47,29,...,18900,F199Q1220923,P,360,2,14,14,0,0,29

In [23]:
# Enregistrer les donn√©es pr√©trait√©es dans un nouveau fichier CSV
bd.to_csv('LoantExport.csv', index=False)

In [25]:
from google.colab import files

# T√©l√©charger le fichier CSV
files.download('LoantExport.csv')